# Generated by Django 5.1.4 on 2026-06-08 21:12

import features.users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', features.users.manager.UserManager()),
            ],
        ),
    ]
