# Generated by Django 5.1.4 on 2026-06-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_message_options_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(verbose_name='Body'),
        ),
    ]
