# Generated by Django 5.1.4 on 2026-06-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(max_length=250, verbose_name='Body'),
        ),
    ]
